resources:
  pipelines:
   - pipeline: Test2
     source: Test2
     project: oct24
     trigger: true
  containers:
  - container: ACRResourceLatest
    type: ACR
    azureSubscription: Azure_Manual
    resourceGroup: RMDev
    registry: abhisheaAcr
    repository: conrepo11
    trigger: true

stages:
  - stage: ConsumedPipelines
    jobs:
    - job: J6
      pool: 
        name: Default
      steps:
       - download: Test2
  - stage: ConsumedContainer
    jobs:
    - job: download_specific_artifact1
      displayName: download specific artifact1
      pool:
        name: Default
      steps:
        - task: PowerShell@2
          inputs:
            targetType: 'inline'
            script: |
              Write-Host $(resources.container.ACRResourceLatest.type)
              Write-Host $(resources.container.ACRResourceLatest.registry)
              Write-Host $(resources.container.ACRResourceLatest.repository)
              Write-Host $(resources.container.ACRResourceLatest.tag)
              Write-Host $(resources.container.ACRResourceLatest.digest)
              Write-Host $(resources.container.ACRResourceLatest.location)


